server:
  port: 8085


spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ankitpathak530/EcommerceConfigServer
          clone-on-start: true
          search-paths: /


