server:
  port: 0


spring:
  application:
    name: CartItem-Service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8085/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - *
  endpoint:
    health:
      show-details: ALWAYS
      logging:
